const posts = [
  {
    id: "who-am-i",
    title: "Iyo Numä, Who Am I",
    category: "Personal",
    tags: ["Personal", "Q&A"],
    preview: "Who I am as Iyo Numä, the perspective behind the work, and the Southern influences shaping my voice.",
    content: `<p>Hi, I'm Iyo Numä, an American writer and the founder of NaRye Studios. I was raised in East Alabama, and my work is deeply shaped by my Southern upbringing, African American culture, and spiritual beliefs.</p><p>I am a self-taught conceptual storyteller, developing narratives from feeling and observation rather than traditional structure. My work moves across psychological horror, drama, and introspective storytelling, with a strong emphasis on atmosphere, tension, and internal experience.</p><p>Much of my work exists within the realm of folklore with psychological horror undertones, which is why I identify as a Psychological Horror Folklore Writer.</p><p>Currently I maintain a limited public presence, choosing to share my work selectively while continuing to develop projects through my studio.</p>`
  },
  {
    id: "why-folklore-why-horror",
    title: "Why folklore, why horror?",
    category: "Horror",
    tags: ["Horror", "Folklore", "Personal"],
    preview: "Why horror and folklore kept appearing in the writing before I had language for what I was doing.",
    content: `<p>For me, the short answer? I didn't choose it—it showed up in my writing before I even knew what to call it.</p><p>I kept noticing the same emotional and unsettling tone in a lot of my work. It felt folkloric. Even when I wasn't trying to write horror, it was there.</p><p>Over time, that tone naturally shifted into psychological horror. And instead of fighting it—I leaned into it.</p><p>When I was trying to figure myself out as a writer, I asked myself a simple question: If I had to be known for one movie—any movie—what would it be? Without hesitation, I said <em>Sleepwalkers</em>.</p><p>It wasn't just the plot for me. It was the tone. The feeling. The imagination. The tension. The fact that it didn't explain everything, but you still felt it.</p><p>And then Jordan Peele stepped into horror. Coming from comedy into something darker—and doing it his own way—it shifted how I saw the genre completely. It showed me that horror has range, and that you can talk about real, uncomfortable things and still make people lean in.</p><p>It also made something clear: there's still room for more Black voices in this space—not just to be present, but to say things that might not land the same way in other genres.</p>`
  },
  {
    id: "where-folklore-falls",
    title: "Where does folklore fall in traditional literature?",
    category: "Folklore",
    tags: ["Folklore", "Q&A"],
    preview: "How folklore moves through poetry, prose, mythology, and the stories people carry across generations.",
    content: `<p>Folklore doesn't sit in one place—it moves through everything.</p><p>A poem is a form of writing that focuses on rhythm, sound, and feeling as much as meaning. Prose is the most natural form of writing—how we normally speak and write in sentences and paragraphs. Mythology is a collection of traditional stories, often involving gods, spirits, or supernatural forces, used to explain the world, human behavior, or natural events.</p><p>Folklore is the body of stories, beliefs, customs, and warnings passed down through people—usually by word of mouth—over time. It doesn't always have a clear origin or author, and it often blends truth, experience, and imagination.</p><p>Folklore is the thread that runs through all of it. It can show up as a poem, take shape in prose, or exist as myth—but at its core, it's something carried. Passed between people, across generations, across places.</p><p>That's why the same warnings, the same patterns, the same feelings appear in different cultures. Not because they were copied—but because they were lived.</p>`
  },
  {
    id: "how-horror-originated",
    title: "How did horror originate? The main genres & subgenres",
    category: "Horror",
    tags: ["Horror", "Q&A"],
    preview: "Horror as warning, boundary, consequence—and how those ideas evolved into modern subgenres.",
    content: `<p>Horror, as a genre, did not begin as the form of entertainment it is today. It more than likely originated as stories created to warn, instruct, and preserve a sense of order.</p><p>Don't go there. Don't touch that. Don't say this.</p><p>There were always rules. Whether those warnings were rooted in spiritual belief, environmental danger, or social control, they carried weight. And when those rules were broken, the stories that followed became what we would now recognize as horror.</p><p><strong>Psychological Horror</strong> focuses on the instability of the mind—fear, identity, perception, and control.</p><p><strong>Supernatural Horror</strong> explores forces beyond the natural world, including spirits, possession, and unseen entities.</p><p><strong>Folk Horror</strong> draws from cultural beliefs, rituals, and inherited traditions—often tied to land, ancestry, and communal memory.</p><p><strong>Slasher</strong> centers on physical threat, typically through a human antagonist, emphasizing violence and survival.</p><p><strong>Body Horror</strong> examines transformation and the loss of control over the human body.</p><p><strong>Survival Horror</strong> places characters in extreme conditions where endurance and escape become central.</p><p>Despite its evolution, horror has remained consistent in one essential way: it begins with recognition. It's that unsettling moment when something familiar becomes unfamiliar.</p>`
  },
  {
    id: "why-do-we-tell-stories",
    title: "Why do we tell stories?",
    category: "Storytelling",
    tags: ["Storytelling", "Folklore", "Personal"],
    preview: "Stories connect experience with listener, preserve memory, and give shape to what lingers.",
    content: `<p>When I was about 10 years old, I was responsible for watching my siblings during the hour gap when my parents weren't home. My dad worked nights, and my mom worked days, so she'd get us ready for school and be back about an hour after we got off the bus.</p><p>The rules were clear: don't go outside, don't open the door, don't answer the phone, don't cook—and don't bring anything from outside into the house.</p><p>When we broke the rules, we thought we were being careful. We stayed in the backyard, quiet enough not to be noticed. Close enough to feel safe—like it didn't really count.</p><p>That's when my little sister found twelve smooth, marbled rocks lined perfectly along the creek near the woods.</p><p>We brought them inside. Nothing happened at first. Then she started waking up at night, saying something was snatching the pillow from under her head. Soon after, the two back rooms felt off. Heavy. Cold. Too quiet.</p><p>Then one night, I saw it. Tall. Thin. Darker than the room itself. It moved strangely—almost like it was gliding. I didn't see its face. Its back was turned as it moved slowly toward the other bed.</p><p>My sister screamed and ran out of the room. The rest of us followed. The house wasn't ours anymore. The hallway stretched longer than it should have. Bright colors flashed while darkness closed in behind us. Everything turned red. Doors appeared where they didn't belong.</p><p>We escaped. We returned home days later with Reverend Thomas, other church members, and my grandmother. We never brought anything from outside inside again. And none of us ever forgot that night.</p><p>Why do we tell stories? We tell stories because we want to connect our experiences with the listener—we want to be understood, felt, to not carry things alone. Stories give shape to what lingers, and sometimes say what we never could out loud.</p><h3>Mechanics of a Simple Story</h3><ol><li><strong>Problem</strong> — What’s the issue? Why does it matter?</li><li><strong>Complication</strong> — What happens because of it?</li><li><strong>Resolution</strong> — What changes?</li></ol><p>That's it—a story is simply something happening, something shifting, and something changing.</p><h3>Griots &amp; Shamans</h3><p>Griots and shamans served different roles across cultures, but both were keepers of knowledge and meaning. Griots, rooted in West African traditions, preserved history, lineage, and cultural memory through storytelling, music, and oral tradition. Shamans acted as spiritual intermediaries—interpreting the unseen, offering healing, and guiding communities through uncertainty.</p><p><strong>Stories emotionally connect us.<br>Folklore teaches you the rules.<br>Horror is what happens when you break them.</strong></p>`
  }
];